# -*- coding: utf-8 -*-
"""OCR.ipynb
efgjd
Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17OoNvGdHxfiq9tLnyDfZ0PbKwZSJ0dWe
"""

!sudo apt install tesseract-ocr
!pip install pytesseract --quiet

!pip install streamlit --quiet
!pip install pyngrok==4.1.1 --quiet
from pyngrok import ngrok

# %%writefile app.py
import streamlit as st
import pytesseract 
from PIL import Image

st.title("Optical Character Recognition")
st.text("Upload the image")

upload = st.file_uploader("Choose an Image")

if upload is not None:

  img = Image.open(upload)
  st.image(img,caption='Uploaded Image',use_column_width=True)
  
  if st.button('Predict'):
    st.write("RESULT......")
    extract = pytesseract.image_to_string(img)
    st.write(extract)

# !nohup streamlit run app.py &
# url = ngrok.connect(port='8501')
# url
